[package]
name = "ctclib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "~0.2"
pdqselect = "~0.1"
kenlm-sys = { path = "kenlm-sys", version = "0.1.0" }
thiserror = "1.0.30"
dhat = { version = "0.3.0", optional = true }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "decode"
harness = false

[features]
dhat-heap = ["dhat"]
